vo=gpu-next
gpu-context=wayland

# 循环单个文件
# loop-file=inf

# 循环播放列表
loop-playlist=inf

# 开启精准进度条
# hr-seek=yes

# 截图相关
screenshot-directory=~/Downloads
screenshot-format=png
screenshot-png-compression=7
