config_version: "201129"

schema_list:
  - schema: yz_pinyin

menu:
  page_size: 5

# punctuator:
#   half_shape:
#     ',' : '，'
#     '.' : '。'
#     '?' : '？'
#     ';' : '；'
#     ':' : '：'
#     '!' : '！'
#     '(' : '（'
#     ')' : '）'
#     '[' : '「'
#     ']' : '」'
#     '"' : { pair: [ '“', '”' ] }
#     '\' : '、'

key_binder:
  bindings:
    - { when: has_menu, accept: minus, send: Page_Up }
    - { when: has_menu, accept: equal, send: Page_Down }
    # - { when: always, accept: Control+space, toggle: ascii_mode }

ascii_composer:
  good_old_caps_lock: true    # true 切换大写，false 切换中英

  # 不同的选项表示：打字打到一半时按下了 CapsLock、Shift、Control 后:
  # commit_code     上屏原始的编码，然后切换到英文
  # commit_text     上屏拼出的词句，然后切换到英文
  # clear           清除未上屏内容，然后切换到英文
  # inline_ascii    切换到临时英文模式，按回车上屏后回到中文状态
  # noop            屏蔽快捷键，不切换中英，但不要屏蔽 CapsLock
  switch_key:
    Shift_L: clear
    Shift_R: clear
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
    Eisu_toggle: clear
