#!/usr/bin/env bash

# riverctl, arch wiki: https://man.archlinux.org/man/riverctl.1
# 
# 关于 river-classic, 作者的回复: https://lobste.rs/s/p21oso
# 
# List of Window Managers: https://codeberg.org/river/wiki/src/branch/main/pages/wm-list.md
# Useful Software: https://codeberg.org/river/wiki/src/branch/main/pages/useful-software.md
# 
# 如果要重新加载配置, 直接手动执行对应的脚本就行了
# 除了 autostart.sh 需要提前判断以外, 其他都是可以重复执行的

source "$HOME/.config/river/config.d/autostart.sh"
source "$HOME/.config/river/config.d/settings.sh"
source "$HOME/.config/river/config.d/binds.sh"
source "$HOME/.config/river/config.d/rules.sh"

"$WM_SCRIPTS/play_audio.sh" "service-login.oga"
