# misc
alias v='nvim'
alias px='http_proxy=http://127.0.0.1:2080 https_proxy=http://127.0.0.1:2080'
alias mpv='px mpv'
alias yt='px yt-dlp'
alias fpi='px flatpak install --user -y flathub'
alias bn='bat -n'
alias bd='bat -d'
alias bp='bat -p'
alias l='eza -lab --time-style="+%y%m%d %H:%M"'
alias lt='l --sort=modified'
alias fm='thunar . > /dev/null 2>&1'
alias mm='nvim /workspace/tmp/mm_$(date +"%y%m%d_%H%M%S").md'
alias cnt='printf "dirs: %s  symlinks: %s  files: %s\n" "$(fd -IH -t d -d 1 | wc -l)" "$(fd -IH -t l -d 1 | wc -l)" "$(fd -IH -t f -d 1 | wc -l)"'
alias du1='du -ah -d 1 .'
alias duf='duf -only local'
# alias cpwd='pwd | wl-copy -n'
alias update='yay -Syyu'

# base
alias _='sudo'
alias 1='cd -1'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'
alias ls='ls --color=auto'
alias ll='ls -alh'
alias mv='mv -i'
alias cp='cp -i'
alias r='printf "zsh: r command disabled\n"'
alias fc='printf "zsh: fc command disabled\n"'

# docker
alias dstopall='sudo docker stop $(sudo docker ps -q)'
alias dstartall='sudo docker start $(sudo docker ps -qa)'
alias dstop='sudo docker stop'
alias dstart='sudo docker start'
alias dcup='sudo docker compose up -d'
alias dis='sudo docker images'
alias dps='sudo docker ps'
alias dec='sudo docker exec -it'
alias drm='sudo docker rm'
alias drmi='sudo docker rmi'
alias dvp='sudo docker volume prune'
alias dlg='sudo docker logs'

# tmux
alias tls='tmux ls'
alias tn='tmux new'
alias tns='tmux new -s'
alias ta='tmux attach'
alias tat='tmux attach -t'
alias tks='tmux kill-session -t'
alias tksall='tmux kill-server'

