# misc
alias cl='reset'
alias v='nvim'
alias px='http_proxy=http://127.0.0.1:2080 https_proxy=http://127.0.0.1:2080'
alias flatpak='px flatpak'
alias mpv='px mpv'
alias yt-dlp='px yt-dlp'
alias yt='px yt-dlp'
alias ryc='rsync -avh --progress'
alias uvdev='source /opt/venvs/dev/bin/activate'
alias uva='source .venv/bin/activate'
alias bn='bat -n'
alias bd='bat -d'
alias bp='bat -p'
alias l='eza --long --all --binary --time-style="+%y%m%d %H:%M"'
alias lf='l --only-files'
alias lt='l --sort=modified'
alias fm='dolphin . > /dev/null 2>&1'
alias kw='kwrite'
alias mm='systemd-run --user --service-type=exec kwrite ~/workspace/tmp/memo_$(date +"%y%m%d_%H%M%S").md'
alias cnt='printf "dirs: %s  symlinks: %s  files: %s\n" "$(fd -IH -t d -d 1 | wc -l)" "$(fd -IH -t l -d 1 | wc -l)" "$(fd -IH -t f -d 1 | wc -l)"'
# alias code='code --unity-launch --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto > /dev/null 2>&1'
alias code='code --ozone-platform-hint=auto > /dev/null 2>&1'
alias y='yazi'

# base
alias _='sudo '
alias 1='cd -1'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'
alias history='fc -lf 1'

# docker
alias dstopall='sudo docker stop $(sudo docker ps -q)'
alias dstartall='sudo docker start $(sudo docker ps -qa)'
alias dstop='sudo docker stop'
alias dstart='sudo docker start'
alias dcup='sudo docker compose up -d'
alias dis='sudo docker images'
alias dps='sudo docker ps'
alias dec='sudo docker exec -it'
alias drm='sudo docker rm'
alias drmi='sudo docker rmi'
alias dvp='sudo docker volume prune'
alias dlg='sudo docker logs'

# systemctl
alias s_status='sudo systemctl status'
alias s_restart='sudo systemctl restart'
alias s_stop='sudo systemctl stop'
alias s_start='sudo systemctl start'
alias s_enable='sudo systemctl enable'

# tmux
alias tls='tmux ls'
alias tn='tmux new'
alias tns='tmux new -s'
alias ta='tmux attach'
alias tat='tmux attach -t'
alias tks='tmux kill-session -t'
alias tksall='tmux kill-server'

