# 炭灰
background #2E2E2E
# 柔米白/白杏灰
foreground #E5E5E5

cursor #E5E5E5
cursor_text_color #2E2E2E

selection_background #E5E5E5
selection_foreground #2E2E2E

# black
color0 #1E8688
# light
color8 #229799

# red
color1 #F59A9A
# light
color9 #F7AFAF

# green
color2 #81E7AF
# light 
color10 #9EEFC0

# yellow
color3 #E9F5BE
# light
color11 #F2FAD0

# blue
color4 #03A791
# light
color12 #1EB9A5

# magenta
color5 #C5B7C7
# light
color13 #D6CADA

# cyan
color6 #F1BA88
# light
color14 #F7CFA4

# white
color7 #E5E5E5
# light
color15 #F0F0F0
