# ~/.config/foot/foot.ini

# 笔记:
# URl, ctrl + shift + o, 会高亮显示所有链接

app-id=foot
title=foot
locked-title=no

# 内边距
pad=6x6 center

# Monaspace Xenon
# Monaspace Neon
font=0xProto Nerd Font Mono:size=12

# 用鼠标选中文本后, 文本被复制到哪里?
# primary: 只复制到主选择区
# clipboard: 只复制到剪贴板
# both: 同时复制到主选择和剪贴板
selection-target=clipboard


[cursor]
# 样式可选: block (方块), beam (竖线), underline (下划线)
style=block

# 光标闪烁
blink=no

# 设置闪烁频率，单位是毫秒。500 是默认值。
# blink-rate=500


[mouse]
hide-when-typing=yes


[key-bindings]
# 从主选择区粘贴的热键
primary-paste=none

# 复制到剪贴板的热键
clipboard-copy=none

# 从剪贴板粘贴的热键
clipboard-paste=Control+v XF86Paste


[mouse-bindings]
# 从主选择区粘贴的热键
primary-paste=none


[text-bindings]

# 相当于 ctrl + w
\x17=Control+BackSpace


include=~/.config/foot/theme.ini
