# -*- conf -*-

app-id=foot
title=foot
locked-title=no


font=JetBrains Mono:size=12

# todo 这个有几种高亮形式
selection-target=both

# 内边距
pad=6x6 center


[cursor]
# 样式可选: block (方块), beam (竖线), underline (下划线)
style=block

# 开启闪烁
blink=yes

# 设置闪烁频率，单位是毫秒。500 是默认值。
blink-rate=500


[mouse]
hide-when-typing=yes


[key-bindings]
clipboard-paste=Control+v XF86Paste

[colors]
alpha=0.85

background=2E2E2E
foreground=E5E5E5

# Foot 格式: cursor=<光标下的文字颜色> <光标背景色>
cursor=2E2E2E E5E5E5

selection-foreground=2E2E2E
selection-background=E5E5E5

## Normal/regular colors (Palette 0-7)
regular0=2E2E2E  # black (color0)
regular1=F59A9A  # red (color1)
regular2=81E7AF  # green (color2)
regular3=E9F5BE  # yellow (color3)
regular4=35B6A0  # blue (color4)
regular5=C5B7C7  # magenta (color5)
regular6=F4C499  # cyan (color6)
regular7=E5E5E5  # white (color7)

## Bright colors (Palette 8-15)
bright0=8C8C8C   # light black (color8)
bright1=F7AFAF   # light red (color9)
bright2=9EEFC0   # light green (color10)
bright3=F2FAD0   # light yellow (color11)
bright4=3FC0B2   # light blue (color12)
bright5=D6CADA   # light magenta (color13)
bright6=F7CFA4   # light cyan (color14)
bright7=F0F0F0   # light white (color15)
