# ~/.config/foot/foot.ini

# 笔记:
# URl, ctrl + shift + o, 会高亮显示所有链接

app-id=foot
title=foot
locked-title=no

# 内边距
pad=6x6 center

# Monaspace Xenon
# Monaspace Neon
font=JetBrains Mono:size=12.8
# font=Google Sans Code:size=12

# 用鼠标选中文本后, 文本被复制到哪里?
# primary: 只复制到主选择区
# clipboard: 只复制到剪贴板
# both: 同时复制到主选择和剪贴板
selection-target=clipboard


[cursor]
# 样式可选: block (方块), beam (竖线), underline (下划线)
style=block

# 光标闪烁
blink=no

# 设置闪烁频率，单位是毫秒。500 是默认值。
# blink-rate=500


[mouse]
hide-when-typing=yes


[key-bindings]
# 从主选择区粘贴的热键
primary-paste=none

# 复制到剪贴板的热键
clipboard-copy=none

# 从剪贴板粘贴的热键
clipboard-paste=Control+v XF86Paste


[mouse-bindings]
# 从主选择区粘贴的热键
primary-paste=none



[colors]
# 背景透明度
alpha=0.85

background=2E2E2E
foreground=F5F5F5

# <光标下的文字颜色> <光标背景色>
cursor=1F2937 D1D5DB

selection-foreground=1F2937
selection-background=D1D5DB

## regular colors
regular0=2E2E2E  # black
regular1=F59A9A  # red
regular2=81E7AF  # green
regular3=E9F5BE  # yellow
regular4=35B6A0  # blue
regular5=C5B7C7  # magenta
regular6=F4C499  # cyan
regular7=F5F5F5  # white

## bright colors
bright0=8C8C8C   # light black
bright1=F7AFAF   # light red
bright2=9EEFC0   # light green
bright3=F2FAD0   # light yellow
bright4=3FC0B2   # light blue
bright5=FFCCEA   # light magenta
bright6=F7CFA4   # light cyan
bright7=F7F7F7   # light white
