# ~/.config/foot/theme.ini

[colors]
# 背景透明度
alpha=0.75

foreground=F5F5F5
background=1F2126

# <光标下的文字颜色> <光标背景色>
cursor=1F2937 D1D5DB

selection-foreground=1F2937
selection-background=D1D5DB

## regular colors
regular0=565656  # black
regular1=F3A0A0  # red
regular2=86E8B3  # green
regular3=E6F2B8  # yellow
regular4=3ABBA5  # blue
regular5=C9BED0  # magenta
regular6=F6CCA3  # cyan
regular7=F5F5F5  # white

## bright colors
bright0=8C8C8C   # light black
bright1=F6B6B6   # light red
bright2=9AEBC2   # light green
bright3=EDF6CC   # light yellow
bright4=5FCFC0   # light blue
bright5=D8CFE0   # light magenta
bright6=F8DDC0   # light cyan
bright7=FAFAFA   # light white
