# ~/.config/foot/theme.ini

[colors]
# 背景透明度
alpha=0.75

background=1F2126
foreground=F5F5F5

# <光标下的文字颜色> <光标背景色>
cursor=1F2937 D1D5DB

selection-foreground=1F2937
selection-background=D1D5DB

## regular colors
regular0=2E2E2E  # black
regular1=F59A9A  # red
regular2=81E7AF  # green
regular3=E9F5BE  # yellow
regular4=35B6A0  # blue
regular5=C5B7C7  # magenta
regular6=F4C499  # cyan
regular7=F5F5F5  # white

## bright colors
bright0=8C8C8C   # light black
bright1=F7AFAF   # light red
bright2=9EEFC0   # light green
bright3=F2FAD0   # light yellow
bright4=3FC0B2   # light blue
bright5=FFCCEA   # light magenta
bright6=F7CFA4   # light cyan
bright7=F7F7F7   # light white
